//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelBTCAddin.ExcelDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExcelDataService.ExcelDataSoap")]
    public interface ExcelDataSoap {
        
        // CODEGEN: Generating message contract since element name FinancialInstrumentHistoryField from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFinancialInstrumentData_New", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewResponse GetFinancialInstrumentData_New(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequest request);
        
        // CODEGEN: Generating message contract since element name FinancialInstrument from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFinancialInstrumentData_LastTick", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickResponse GetFinancialInstrumentData_LastTick(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequest request);
        
        // CODEGEN: Generating message contract since element name FinancialInstrumentHistoryField from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFinancialInstrumentData", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataResponse GetFinancialInstrumentData(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequest request);
        
        // CODEGEN: Generating message contract since element name GetCETIPAccumulatedCDIResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCETIPAccumulatedCDI", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIResponse GetCETIPAccumulatedCDI(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequest request);
        
        // CODEGEN: Generating message contract since element name GetCETIPAccumulatedCDIWithSpreadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCETIPAccumulatedCDIWithSpread", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadResponse GetCETIPAccumulatedCDIWithSpread(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequest request);
        
        // CODEGEN: Generating message contract since element name valor from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.TestResponse Test(ExcelBTCAddin.ExcelDataService.TestRequest request);
        
        // CODEGEN: Generating message contract since element name valor from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PluralInpuCorporateDesk", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskResponse PluralInpuCorporateDesk(ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequest request);
        
        // CODEGEN: Generating message contract since element name financialInstrumentExchangeCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FXTradingSpotInsert", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertResponse FXTradingSpotInsert(ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequest request);
        
        // CODEGEN: Generating message contract since element name Currency from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FXTradingPendingOccurrenceValueSelect", ReplyAction="*")]
        ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectResponse FXTradingPendingOccurrenceValueSelect(ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFinancialInstrumentData_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFinancialInstrumentData_New", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequestBody Body;
        
        public GetFinancialInstrumentData_NewRequest() {
        }
        
        public GetFinancialInstrumentData_NewRequest(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFinancialInstrumentData_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FinancialInstrumentHistoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double DoubleDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool ExactDate;
        
        public GetFinancialInstrumentData_NewRequestBody() {
        }
        
        public GetFinancialInstrumentData_NewRequestBody(string FinancialInstrumentHistoryField, string Code, double DoubleDate, bool ExactDate) {
            this.FinancialInstrumentHistoryField = FinancialInstrumentHistoryField;
            this.Code = Code;
            this.DoubleDate = DoubleDate;
            this.ExactDate = ExactDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFinancialInstrumentData_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFinancialInstrumentData_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewResponseBody Body;
        
        public GetFinancialInstrumentData_NewResponse() {
        }
        
        public GetFinancialInstrumentData_NewResponse(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFinancialInstrumentData_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetFinancialInstrumentData_NewResult;
        
        public GetFinancialInstrumentData_NewResponseBody() {
        }
        
        public GetFinancialInstrumentData_NewResponseBody(object GetFinancialInstrumentData_NewResult) {
            this.GetFinancialInstrumentData_NewResult = GetFinancialInstrumentData_NewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFinancialInstrumentData_LastTickRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFinancialInstrumentData_LastTick", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequestBody Body;
        
        public GetFinancialInstrumentData_LastTickRequest() {
        }
        
        public GetFinancialInstrumentData_LastTickRequest(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFinancialInstrumentData_LastTickRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FinancialInstrument;
        
        public GetFinancialInstrumentData_LastTickRequestBody() {
        }
        
        public GetFinancialInstrumentData_LastTickRequestBody(string FinancialInstrument) {
            this.FinancialInstrument = FinancialInstrument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFinancialInstrumentData_LastTickResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFinancialInstrumentData_LastTickResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickResponseBody Body;
        
        public GetFinancialInstrumentData_LastTickResponse() {
        }
        
        public GetFinancialInstrumentData_LastTickResponse(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFinancialInstrumentData_LastTickResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetFinancialInstrumentData_LastTickResult;
        
        public GetFinancialInstrumentData_LastTickResponseBody() {
        }
        
        public GetFinancialInstrumentData_LastTickResponseBody(object GetFinancialInstrumentData_LastTickResult) {
            this.GetFinancialInstrumentData_LastTickResult = GetFinancialInstrumentData_LastTickResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFinancialInstrumentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFinancialInstrumentData", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequestBody Body;
        
        public GetFinancialInstrumentDataRequest() {
        }
        
        public GetFinancialInstrumentDataRequest(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFinancialInstrumentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FinancialInstrumentHistoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double DoubleDate;
        
        public GetFinancialInstrumentDataRequestBody() {
        }
        
        public GetFinancialInstrumentDataRequestBody(string FinancialInstrumentHistoryField, string Code, double DoubleDate) {
            this.FinancialInstrumentHistoryField = FinancialInstrumentHistoryField;
            this.Code = Code;
            this.DoubleDate = DoubleDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFinancialInstrumentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFinancialInstrumentDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataResponseBody Body;
        
        public GetFinancialInstrumentDataResponse() {
        }
        
        public GetFinancialInstrumentDataResponse(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFinancialInstrumentDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetFinancialInstrumentDataResult;
        
        public GetFinancialInstrumentDataResponseBody() {
        }
        
        public GetFinancialInstrumentDataResponseBody(object GetFinancialInstrumentDataResult) {
            this.GetFinancialInstrumentDataResult = GetFinancialInstrumentDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCETIPAccumulatedCDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCETIPAccumulatedCDI", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequestBody Body;
        
        public GetCETIPAccumulatedCDIRequest() {
        }
        
        public GetCETIPAccumulatedCDIRequest(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCETIPAccumulatedCDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Percentage;
        
        public GetCETIPAccumulatedCDIRequestBody() {
        }
        
        public GetCETIPAccumulatedCDIRequestBody(System.DateTime StartDate, System.DateTime EndDate, decimal Percentage) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.Percentage = Percentage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCETIPAccumulatedCDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCETIPAccumulatedCDIResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIResponseBody Body;
        
        public GetCETIPAccumulatedCDIResponse() {
        }
        
        public GetCETIPAccumulatedCDIResponse(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCETIPAccumulatedCDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetCETIPAccumulatedCDIResult;
        
        public GetCETIPAccumulatedCDIResponseBody() {
        }
        
        public GetCETIPAccumulatedCDIResponseBody(object GetCETIPAccumulatedCDIResult) {
            this.GetCETIPAccumulatedCDIResult = GetCETIPAccumulatedCDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCETIPAccumulatedCDIWithSpreadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCETIPAccumulatedCDIWithSpread", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequestBody Body;
        
        public GetCETIPAccumulatedCDIWithSpreadRequest() {
        }
        
        public GetCETIPAccumulatedCDIWithSpreadRequest(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCETIPAccumulatedCDIWithSpreadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal SpreadPercentage;
        
        public GetCETIPAccumulatedCDIWithSpreadRequestBody() {
        }
        
        public GetCETIPAccumulatedCDIWithSpreadRequestBody(System.DateTime StartDate, System.DateTime EndDate, decimal SpreadPercentage) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.SpreadPercentage = SpreadPercentage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCETIPAccumulatedCDIWithSpreadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCETIPAccumulatedCDIWithSpreadResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadResponseBody Body;
        
        public GetCETIPAccumulatedCDIWithSpreadResponse() {
        }
        
        public GetCETIPAccumulatedCDIWithSpreadResponse(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCETIPAccumulatedCDIWithSpreadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetCETIPAccumulatedCDIWithSpreadResult;
        
        public GetCETIPAccumulatedCDIWithSpreadResponseBody() {
        }
        
        public GetCETIPAccumulatedCDIWithSpreadResponseBody(object GetCETIPAccumulatedCDIWithSpreadResult) {
            this.GetCETIPAccumulatedCDIWithSpreadResult = GetCETIPAccumulatedCDIWithSpreadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(ExcelBTCAddin.ExcelDataService.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        public TestRequestBody() {
        }
        
        public TestRequestBody(string valor, string code) {
            this.valor = valor;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(ExcelBTCAddin.ExcelDataService.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(object TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PluralInpuCorporateDeskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PluralInpuCorporateDesk", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequestBody Body;
        
        public PluralInpuCorporateDeskRequest() {
        }
        
        public PluralInpuCorporateDeskRequest(ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PluralInpuCorporateDeskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        public PluralInpuCorporateDeskRequestBody() {
        }
        
        public PluralInpuCorporateDeskRequestBody(string valor, string code) {
            this.valor = valor;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PluralInpuCorporateDeskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PluralInpuCorporateDeskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskResponseBody Body;
        
        public PluralInpuCorporateDeskResponse() {
        }
        
        public PluralInpuCorporateDeskResponse(ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PluralInpuCorporateDeskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object PluralInpuCorporateDeskResult;
        
        public PluralInpuCorporateDeskResponseBody() {
        }
        
        public PluralInpuCorporateDeskResponseBody(object PluralInpuCorporateDeskResult) {
            this.PluralInpuCorporateDeskResult = PluralInpuCorporateDeskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXTradingSpotInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXTradingSpotInsert", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequestBody Body;
        
        public FXTradingSpotInsertRequest() {
        }
        
        public FXTradingSpotInsertRequest(ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FXTradingSpotInsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string financialInstrumentExchangeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<decimal> buyPriceD0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> buyPriceD1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> buyPriceD2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> sellPriceD0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> sellPriceD1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<decimal> sellPriceD2;
        
        public FXTradingSpotInsertRequestBody() {
        }
        
        public FXTradingSpotInsertRequestBody(string financialInstrumentExchangeCode, System.Nullable<System.DateTime> date, System.Nullable<decimal> buyPriceD0, System.Nullable<decimal> buyPriceD1, System.Nullable<decimal> buyPriceD2, System.Nullable<decimal> sellPriceD0, System.Nullable<decimal> sellPriceD1, System.Nullable<decimal> sellPriceD2) {
            this.financialInstrumentExchangeCode = financialInstrumentExchangeCode;
            this.date = date;
            this.buyPriceD0 = buyPriceD0;
            this.buyPriceD1 = buyPriceD1;
            this.buyPriceD2 = buyPriceD2;
            this.sellPriceD0 = sellPriceD0;
            this.sellPriceD1 = sellPriceD1;
            this.sellPriceD2 = sellPriceD2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXTradingSpotInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXTradingSpotInsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertResponseBody Body;
        
        public FXTradingSpotInsertResponse() {
        }
        
        public FXTradingSpotInsertResponse(ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FXTradingSpotInsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FXTradingSpotInsertResult;
        
        public FXTradingSpotInsertResponseBody() {
        }
        
        public FXTradingSpotInsertResponseBody(string FXTradingSpotInsertResult) {
            this.FXTradingSpotInsertResult = FXTradingSpotInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXTradingPendingOccurrenceValueSelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXTradingPendingOccurrenceValueSelect", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequestBody Body;
        
        public FXTradingPendingOccurrenceValueSelectRequest() {
        }
        
        public FXTradingPendingOccurrenceValueSelectRequest(ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FXTradingPendingOccurrenceValueSelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Type;
        
        public FXTradingPendingOccurrenceValueSelectRequestBody() {
        }
        
        public FXTradingPendingOccurrenceValueSelectRequestBody(System.DateTime date, string Currency, string Type) {
            this.date = date;
            this.Currency = Currency;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FXTradingPendingOccurrenceValueSelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FXTradingPendingOccurrenceValueSelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectResponseBody Body;
        
        public FXTradingPendingOccurrenceValueSelectResponse() {
        }
        
        public FXTradingPendingOccurrenceValueSelectResponse(ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FXTradingPendingOccurrenceValueSelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal FXTradingPendingOccurrenceValueSelectResult;
        
        public FXTradingPendingOccurrenceValueSelectResponseBody() {
        }
        
        public FXTradingPendingOccurrenceValueSelectResponseBody(decimal FXTradingPendingOccurrenceValueSelectResult) {
            this.FXTradingPendingOccurrenceValueSelectResult = FXTradingPendingOccurrenceValueSelectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExcelDataSoapChannel : ExcelBTCAddin.ExcelDataService.ExcelDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExcelDataSoapClient : System.ServiceModel.ClientBase<ExcelBTCAddin.ExcelDataService.ExcelDataSoap>, ExcelBTCAddin.ExcelDataService.ExcelDataSoap {
        
        public ExcelDataSoapClient() {
        }
        
        public ExcelDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExcelDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.GetFinancialInstrumentData_New(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequest request) {
            return base.Channel.GetFinancialInstrumentData_New(request);
        }
        
        public object GetFinancialInstrumentData_New(string FinancialInstrumentHistoryField, string Code, double DoubleDate, bool ExactDate) {
            ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequest inValue = new ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewRequestBody();
            inValue.Body.FinancialInstrumentHistoryField = FinancialInstrumentHistoryField;
            inValue.Body.Code = Code;
            inValue.Body.DoubleDate = DoubleDate;
            inValue.Body.ExactDate = ExactDate;
            ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_NewResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).GetFinancialInstrumentData_New(inValue);
            return retVal.Body.GetFinancialInstrumentData_NewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.GetFinancialInstrumentData_LastTick(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequest request) {
            return base.Channel.GetFinancialInstrumentData_LastTick(request);
        }
        
        public object GetFinancialInstrumentData_LastTick(string FinancialInstrument) {
            ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequest inValue = new ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickRequestBody();
            inValue.Body.FinancialInstrument = FinancialInstrument;
            ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentData_LastTickResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).GetFinancialInstrumentData_LastTick(inValue);
            return retVal.Body.GetFinancialInstrumentData_LastTickResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.GetFinancialInstrumentData(ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequest request) {
            return base.Channel.GetFinancialInstrumentData(request);
        }
        
        public object GetFinancialInstrumentData(string FinancialInstrumentHistoryField, string Code, double DoubleDate) {
            ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequest inValue = new ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataRequestBody();
            inValue.Body.FinancialInstrumentHistoryField = FinancialInstrumentHistoryField;
            inValue.Body.Code = Code;
            inValue.Body.DoubleDate = DoubleDate;
            ExcelBTCAddin.ExcelDataService.GetFinancialInstrumentDataResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).GetFinancialInstrumentData(inValue);
            return retVal.Body.GetFinancialInstrumentDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.GetCETIPAccumulatedCDI(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequest request) {
            return base.Channel.GetCETIPAccumulatedCDI(request);
        }
        
        public object GetCETIPAccumulatedCDI(System.DateTime StartDate, System.DateTime EndDate, decimal Percentage) {
            ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequest inValue = new ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            inValue.Body.Percentage = Percentage;
            ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).GetCETIPAccumulatedCDI(inValue);
            return retVal.Body.GetCETIPAccumulatedCDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.GetCETIPAccumulatedCDIWithSpread(ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequest request) {
            return base.Channel.GetCETIPAccumulatedCDIWithSpread(request);
        }
        
        public object GetCETIPAccumulatedCDIWithSpread(System.DateTime StartDate, System.DateTime EndDate, decimal SpreadPercentage) {
            ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequest inValue = new ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            inValue.Body.SpreadPercentage = SpreadPercentage;
            ExcelBTCAddin.ExcelDataService.GetCETIPAccumulatedCDIWithSpreadResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).GetCETIPAccumulatedCDIWithSpread(inValue);
            return retVal.Body.GetCETIPAccumulatedCDIWithSpreadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.TestResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.Test(ExcelBTCAddin.ExcelDataService.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public object Test(string valor, string code) {
            ExcelBTCAddin.ExcelDataService.TestRequest inValue = new ExcelBTCAddin.ExcelDataService.TestRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.TestRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.code = code;
            ExcelBTCAddin.ExcelDataService.TestResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.PluralInpuCorporateDesk(ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequest request) {
            return base.Channel.PluralInpuCorporateDesk(request);
        }
        
        public object PluralInpuCorporateDesk(string valor, string code) {
            ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequest inValue = new ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.code = code;
            ExcelBTCAddin.ExcelDataService.PluralInpuCorporateDeskResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).PluralInpuCorporateDesk(inValue);
            return retVal.Body.PluralInpuCorporateDeskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.FXTradingSpotInsert(ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequest request) {
            return base.Channel.FXTradingSpotInsert(request);
        }
        
        public string FXTradingSpotInsert(string financialInstrumentExchangeCode, System.Nullable<System.DateTime> date, System.Nullable<decimal> buyPriceD0, System.Nullable<decimal> buyPriceD1, System.Nullable<decimal> buyPriceD2, System.Nullable<decimal> sellPriceD0, System.Nullable<decimal> sellPriceD1, System.Nullable<decimal> sellPriceD2) {
            ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequest inValue = new ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertRequestBody();
            inValue.Body.financialInstrumentExchangeCode = financialInstrumentExchangeCode;
            inValue.Body.date = date;
            inValue.Body.buyPriceD0 = buyPriceD0;
            inValue.Body.buyPriceD1 = buyPriceD1;
            inValue.Body.buyPriceD2 = buyPriceD2;
            inValue.Body.sellPriceD0 = sellPriceD0;
            inValue.Body.sellPriceD1 = sellPriceD1;
            inValue.Body.sellPriceD2 = sellPriceD2;
            ExcelBTCAddin.ExcelDataService.FXTradingSpotInsertResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).FXTradingSpotInsert(inValue);
            return retVal.Body.FXTradingSpotInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectResponse ExcelBTCAddin.ExcelDataService.ExcelDataSoap.FXTradingPendingOccurrenceValueSelect(ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequest request) {
            return base.Channel.FXTradingPendingOccurrenceValueSelect(request);
        }
        
        public decimal FXTradingPendingOccurrenceValueSelect(System.DateTime date, string Currency, string Type) {
            ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequest inValue = new ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequest();
            inValue.Body = new ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectRequestBody();
            inValue.Body.date = date;
            inValue.Body.Currency = Currency;
            inValue.Body.Type = Type;
            ExcelBTCAddin.ExcelDataService.FXTradingPendingOccurrenceValueSelectResponse retVal = ((ExcelBTCAddin.ExcelDataService.ExcelDataSoap)(this)).FXTradingPendingOccurrenceValueSelect(inValue);
            return retVal.Body.FXTradingPendingOccurrenceValueSelectResult;
        }
    }
}
